services:
  - type: web
    name: smart-research-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true
    envVars:
      - key: TAVILY_API_KEY
        value: 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
      - key: GOOGLE_API_KEY
        sync: false
